### ISSUE TITLE
published name doesn't match embedded application name

### ISSUE THREAD

**Issue by akhepcat** [diejuse/bashblitz#1]
At  https://github.com/diejuse/bashfritz/blob/b97c28e2c703f8eec95055b544cef0089502b9ff/bashfritz.sh#L98
the program is hardcoded with the embedded name "BASHBLITZ"

however filename and published name is 'bashfritz'

this may cause some confusion.  :-) 

(I did not scan for other occurrences - if there are multiple, this could be mitigated with a variable. :-)  )

**Comment by diejuse** [comment]
I had a mistake. Thanks for your warning. I am changing the name.
